### ISSUE TITLE
Suggestions, TODO

### ISSUE THREAD

**Issue by gr33nd3v1l** [gosimulate/gosimulator#23]
**In order of importance:**

- [ ] Use Great Ball and Ultra balls
- [ ] Start/Pause/Stop buttons
- [ ] Export pokemon transfer\evolve settings
- [ ] "Circular route" selection for circular or linear routes (Turn around or start from beginning) #107 
- [x] IV/CP toggle confusion #89 
- [x] User defined custom routes
- [x] Manual pokemon list for evolution or transfer
-   _OR_ Manual transfer\evolve buttons
- [x] Pokemon slots display
- [x] Bag slots display
- [ ] Statistics (Catch, Evolve, Transfer, Item statistics display when bot ends / is running) #94 
- [ ] 12hr timer to avoid ban due to length of playing/Custom timer for automatic simulator on/off
- [ ] Move exp bar below name (allows for one more row of log)
- [ ] Replace "Is google account (Betatesting)?" with "Google account No/Yes)
-  _OR_ Make selection for PTC and Google account
- [x] Custom user defined routes
- [x] User defined movement speed
- [ ] User defined amount of potions and items

 **Spelling fixes**

- [ ] "Read last coordiante ... " > "Read last coordinate from file. Turning around."
- [ ] "Melburne" and "Melburne Lillydale lake" > "Melbourne"
- [ ] "Removed soft bann, congratz :)" > "Softban removed :) Congratulations!"
- [ ] Catch ..pokemon > Caught ..pokemon
- [x] "Use rasperies to catch pokemons" > "Use Raspberries to catch pokemon"

**Comment by gr33nd3v1l** [comment]
Added a few more things

**Comment by gr33nd3v1l** [comment]
Add:
12hr timer

**Comment by richardhanooman** [comment]
- Catch to caught. 
- Option to set route path. Point A to Point B. Reverse when reach end B to A. (Makes it easier instead of adding routes manually) 
-Adfree version (will pay to play)

**Comment by gr33nd3v1l** [comment]
More included

**Comment by richardhanooman** [comment]
Pokemon settings list to save. Backup and restore so I don't have to go to each Pokemon again and adjust the evolve and transfer Cp after I uninstall the app or clear Data.

**Comment by djfaizp** [comment]
Which will features will be in next release beacuse i am to excited to know about it @gosimulator

**Comment by insider111** [comment]
please change the display to make it more interesting and change the look of app potrait > landscape to be more comprehensive

**Comment by gosimulate** [comment]
If u press save on one pokemon ( not save for all) it would save for just that pokemon. CLosing one todo

**Comment by gr33nd3v1l** [comment]
Custom movement speeds added in 1.10.1

**Comment by azziejay** [comment]
please also use the great ball and the ultra ball to capture pokemons

**Comment by Phanthropogenic** [comment]
Use it for certain CPs and/or Pokemons. (Such as Gyarados, Farfetch'd, etc.) @azziejay

**Comment by azziejay** [comment]
@Phanthropogenic up

**Comment by gr33nd3v1l** [comment]
It is being worked on :)

**Comment by kingkai808** [comment]
Would be nice to have transfer/evolve from bag. I know it keeps the strongest of each pokemon but i want to be able to delete duplicates as auto transfer is not doing it. 
Use great ball/ultra ball when out of poke balls.
Transfer by iv has to also has to have transfer by cp toggled on as well to work. Got confusing.
New ban algorithm is out. Getting higher than 150k xp per hour will result in being flagged as botting which will be banned. Maybe add a warning cp cap will be reached soon? Or auto stop if you're too close to it?

**Comment by MarcoBelinea** [comment]
http://www.pc-magazin.de/ratgeber/pokemon-go-namen-deutsch-englisch-uebersetzt-liste-3196559.html

German Names for Pokes

German	English

Abra	Abra
Aerodactyl	Aerodactyl
Alpollo	Haunter
Amonitas	Omanyte
Amoroso	Omastar
Aquana	        Vaporeon
Arbok.            Arbok
Arkani.    	Arcanine
Arktos     	Articuno
Austos.    	Cloyster
Bibor.      	Beedrill
Bisaflor   	Venusaur
Bisaknosp	Ivysaur
Bisasam 	Bulbasaur
Blitza.     	Jolteon
Bluzuk.   	Venonat
Chaneira	Chansey
Digda.     	Diglett
Digdri      	Dugtrio
Ditto.       	Ditto
Dodri.      	Dodrio
Dodu.      	Doduo
Dragonir	        Dragonair
Dragoran	Dragonite
Dratini.    	Dratini
Duflor.     	Gloom
Elektek.  	Electabuzz
Enton.     	Psyduck
Entoron. 	Golduck
Evoli.       	Eevee
Flamara. 	Flareon
Flegmon	        Slowpoke
Fukano.  	Growlithe
Gallopa.  	Rapidash
Garados 	Gyarados
Gengar.   	Gengar
Georok.   	Graveler
Geowaz. 	Golem
Giflor.      	Vileplume
Glumanda	Charmander
Glurak.    	Charizard
Glutexo.  	Charmeleon
Golbat.    	Golbat
Goldini.   	Goldeen
Golking.  	Seaking
Habitak. 	Spearow
Hornliu.  	Weedle
Hypno.    	Hypno
Ibitak.     	Fearow
Jugong.  	Dewgong
Jurob.     	Seel
Kabuto.   	Kabuto
Kabutops	Kabutops
Kadabra 	Kadabra
Kangama	Kangaskhan
Karpador	Magikarp
Kicklee.  	Hitmonlee
Kingler.   	Kingler
Kleinstein	Geodude
Knofensa	Bellsprout
Knogga.  	Marowak
Knuddeluff	Wigglytuff
Kokowei 	Exeggutor
Kokuna.  	Kakuna
Krabby.   	Krabby
Lahmus. 	Slowbro
Lapras    	Lapras
Lavados 	Moltres
Lektrobal	Electrode
Machollo	Machop
Machomei	Machamp
Magmar 	Magmar
Magnetilo	Magnemite
Magneton	Magneton
Maschock	Machoke
Mauzi.    	Meowth
Menki.    	Mankey
Mew.       	Mew
Mewtu.   	Mewtwo
Muschas	Shellder
Myrapla. 	Oddish
Nebulak. 	Gastly
Nidoking	Nidoking
Nidoqueen	Nidoqueen
Nidoran (m)	Nidoran (m)
Nidoran (f)	Nidoran (f)
Nidorina.  	Nidorina
Nidorino	        Nidorino
Nockchan	Hitmonchan
Omot	        Venomoth
Onix	        Onix
Owei	        Exeggcute
Pantimos	Mr. Mime
Paras.     	Paras
Parasek. 	Parasect
Piepi.      	Clefairy
Pikachu. 	Pikachu
Pinsir.     	Pinsir
Pixi.         	Clefable
Ponita.    	Ponyta
Porenta.  	Farfetchd
Porygon. 	Porygon
Pummeluff	Jigglypuff
Quappo. 	Poliwrath
Quapsel. 	Poliwag
Quaputzi	Poliwhirl
Raichu.   	Raichu
Rasaff.   	Primeape
Rattfratz	        Rattata
Rattikarl.	Raticate
Raupy.    	Caterpie
Relaxo.   	Snorlax
Rettan.    	Ekans
Rihorn.   	Rhyhorn
Rizeros.  	Rhydon
Rossana        Jynx
Safcon    	Metapod
Sandamer	Sandslash
Sandan.  	Sandshrew
Sarzenia. 	Victreebel
Schiggy. 	Squirtle
Schillok.  	Wartortle
Schlurp.  	Lickitung
Seemon. 	Seadra
Seeper.   	Horsea
Sichlor.   	Scyther
Simsala   	Alakazam
Sleima.   	Grimer
Sleimok.  	Muk
Smettbo 	Butterfree
Smogmog	Weezing
Smogon 	Koffing
Snobilikat	Persian
Starmie. 	Starmie
Sterndu. 	Staryu
Tangela. 	Tangela
Tauboga 	Pidgeotto
Tauboss	        Pidgeot
Taubsi.   	Pidgey
Tauros.   	Tauros
Tentacha	Tentacool
Tentoxa.  	Tentacruel
Tragosso	Cubone
Traumato	Drowzee
Turtok.    	Blastoise
Ultrigaria	Weepinbell
Voltobal.  	Voltorb
Vulnona.  	Ninetales
Vulpix.    	Vulpix
Zapdos    	Zapdos
Zubat.     	Zubat

That were great
