### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by narutouchi55** [gosimulate/gosimulator#315]
- [ ] Fix the issue with the PTC accounts (Failed to log in. Your account is probably banned. Please try with official app.)
- [ ] Fix exp and similar not updating upon loot, or pokemon catch ( #301 )
- [ ] Fix english translation (grammar and spelling) - http://pastebin.com/hJ68FejD (From manor7777)
- [ ] Add Gosim auto randomize slight variation in coordinates between poke stops. #349
- [ ] Implement Malay translation ( #249 )
- [ ] Fix spanish translation ( #310 )
- [ ] Provide an archive of downloads for those who want it (why would you?!) - @manor7777 can provide hosting for free if required, though you will need a domain name!
- [x] Be able to see your items (potions, pokeballs, etc) inside your bag
- [ ] Be able to save your bot and pokemon settings 
- [ ] Better portuguese translation ( #346 )
- [ ] Check the Dusseldorf route ( #279 )
- [ ] Stop the bot at 12 hours of use or at 1k pokemons or at 2k pokestops. ( #348 )
- [ ] Add play/pause/stop 
- [x] Add a pokestop only mode ( #359 )

**Comment by gosimulate** [comment]
Latest version has items (potions, pokeballs) in bag

**Comment by manor7777** [comment]
Last night rearranged issues in priority order, ones at the top should be fixed first :)
